# Template pipeline for deploying SAM lambdas to AWS
# Mike Zazon - Quantum Health
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - subdir12/*

stages:
- stage: DeployCFN
  jobs:
  - job: DeployCFN
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CloudFormationCreateOrUpdateStack@1
      displayName: 'Create/Update Stack: aws-fargate-nginx-proxy'
      inputs:
        awsCredentials: 'qh-aws-ss-prod-acct'
        regionName: 'us-east-2'
        stackName: 'aws-fargate-nginx-proxy'
        templateSource: 'file'
        templateFile: 'subdir12/nginx-proxy-cfn.yaml'
        useChangeSet: true
        changeSetName: 'Fargate-NGINX-Change-Set'